version: '3.7'
services:
  messaging:
    image: "rabbitmq:3-management"
    expose: 
      - 5672
    ports:
      - "15672:15672"
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - type: volume
        source: db_data
        target: /data/db
  server:
    build: ./server
    depends_on:
      - db
      - messaging
    ports:
      - "5000:5000"
  web:
    build: ./web
    depends_on:
      - server
    ports:
      - "80:80"
volumes:
  db_data: